from django.urls import path
from . import views
urlpatterns = [
    path('sales/', views.sales_master, name='sales'),
    path('sales_product/', views.sales_product, name='sales_product'),
    path('UpdateSalesProduct/<id>', views.Update_product_detail,
         name='update_sales_product'),
    path('Update_sales/<id>', views.update_sales, name='update_sales'),
    path('Sales_ret_has_product/<id>', views.sales_ret_has_prod,
         name="sales_ret_has_product"),
    path('delete_sales/<id>', views.delete_sales, name='delete_sales'),
    path('delete_sales_product/<id>', views.delete_sales_product,
         name='delete_sales_product'),
    path('salesreturn/<id>', views.salesreturn, name='sales_return'),
    path('saless_return/', views.saless_return, name='saless_return'),
    path('sales_return_product/<id>', views.sales_return_product,
         name='sales_return_product'),
    path('Update_sales_return/<id>', views.Update_Sales_Return,
         name='update_sales_return'),
    path('delete_salesreturn/<id>', views.delete_salesreturn,
         name='delete_salesreturn'),
    # path('deletereturnproduct/<id>',views.deletepurchase_return_product,name='deletereturnproduct'),
    path('delete_salesreturn_product/<id>',
         views.delete_salesreturn_product, name='delete_salesreturn_product'),
    path('UpdateSalesReturnProduct/<id>', views.update_sales_return_product,
         name='update_sales_return_product'),
    path('UpdateSalesReturnHasProduct/<id>',
         views.update_sales_ret_has_prod, name='update_sales_ret_has_prod'),
    path('pdf_view/<id>', views.ViewPDF.as_view(), name="pdf_view"),
    #path('invoice/<id>', views.invoice, name="invoice"),
]
