# Generated by Django 3.0.7 on 2020-10-19 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupervisorHasWarehouse',
        ),
    ]
