# Generated by Django 3.0.7 on 2020-10-19 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('purchase', '0003_supervisorhaswarehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorHasCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.Company')),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.Supervisor')),
            ],
        ),
    ]
