# Generated by Django 3.0.6 on 2020-10-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_supervisorhascompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportation',
            name='address',
            field=models.TextField(max_length=120, null=True),
        ),
    ]
