# Generated by Django 3.0.7 on 2021-02-20 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_transportation_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereturn',
            name='purchase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.Purchase'),
        ),
    ]
