# Generated by Django 3.0.7 on 2021-02-22 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_purchasereturn_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasereturn',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='purchase.Supplier'),
        ),
    ]
