# Generated by Django 3.0.6 on 2021-03-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0008_auto_20210312_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='mobile',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
