# Generated by Django 3.0.6 on 2021-03-18 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0009_auto_20210312_1919'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupervisorHasCompany',
        ),
    ]
