# Generated by Django 3.0.6 on 2021-03-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0010_delete_supervisorhascompany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportation',
            name='mobile',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
