# Generated by Django 3.0.6 on 2021-03-23 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20210318_1920'),
        ('purchase', '0011_auto_20210321_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorHasCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.Company')),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.Supervisor')),
            ],
        ),
    ]
