# Generated by Django 3.0.6 on 2021-03-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0012_supervisorhascompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
