# Generated by Django 3.0.6 on 2021-03-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0013_transportation_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hole_size',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='holes',
            field=models.IntegerField(null=True),
        ),
    ]
