# Generated by Django 3.0.6 on 2021-03-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0014_auto_20210329_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='hole_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='holes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
