# Generated by Django 3.0.7 on 2021-05-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0016_auto_20210505_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='hole_size',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='holes',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
