# Generated by Django 3.0.7 on 2021-05-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0017_auto_20210509_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='holes',
            field=models.CharField(default=' ', max_length=20),
        ),
    ]
