# Generated by Django 3.0.7 on 2021-05-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0018_auto_20210509_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='hole_size',
            field=models.CharField(default=' ', max_length=20),
        ),
    ]
