# Generated by Django 3.0.6 on 2021-03-20 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20210318_1920'),
        ('dispatch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Area'),
        ),
        migrations.AddField(
            model_name='plant',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Company'),
        ),
    ]
