# Generated by Django 3.0.6 on 2021-03-23 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0012_supervisorhascompany'),
        ('dispatch', '0002_auto_20210320_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse_To_Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatch.Plant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.Warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse_To_Plant_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='purchase.Product')),
                ('warehouse_to_plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatch.Warehouse_To_Plant')),
            ],
        ),
        migrations.CreateModel(
            name='plant_Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(blank=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatch.Plant')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='purchase.Product')),
            ],
        ),
    ]
