# Generated by Django 3.0.6 on 2021-03-24 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0013_transportation_is_active'),
        ('dispatch', '0003_plant_stock_warehouse_to_plant_warehouse_to_plant_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse_to_plant',
            name='expense',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='warehouse_to_plant',
            name='truck_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='warehouse_to_plant',
            name='truck_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='purchase.Transportation'),
        ),
        migrations.AddField(
            model_name='warehouse_to_plant',
            name='weight',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
