# Generated by Django 3.0.6 on 2021-03-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0004_auto_20210324_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse_to_plant',
            name='expense',
            field=models.IntegerField(null=True),
        ),
    ]
