# Generated by Django 3.0.6 on 2021-03-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0005_auto_20210324_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse_to_plant',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
