# Generated by Django 3.0.6 on 2021-03-29 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0014_auto_20210329_1643'),
        ('inventory', '0009_auto_20210318_1920'),
        ('dispatch', '0006_warehouse_to_plant_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('truck_no', models.CharField(blank=True, max_length=50, null=True)),
                ('weight', models.CharField(max_length=30, null=True)),
                ('expense', models.IntegerField(null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Customer')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatch.Plant')),
                ('truck_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='purchase.Transportation')),
            ],
        ),
    ]
