# Generated by Django 3.0.6 on 2021-04-08 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20210318_1920'),
        ('dispatch', '0008_dispatchdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='dealer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Dealer'),
        ),
    ]
