# Generated by Django 3.0.6 on 2021-04-08 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0015_auto_20210329_1658'),
        ('inventory', '0009_auto_20210318_1920'),
        ('dispatch', '0009_dispatch_dealer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('truck_no', models.CharField(blank=True, max_length=50, null=True)),
                ('weight', models.CharField(max_length=30, null=True)),
                ('expense', models.IntegerField(null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Customer')),
                ('dealer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Dealer')),
                ('truck_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='purchase.Transportation')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.Warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(null=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatch.Collection')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.Product')),
            ],
        ),
    ]
