# Generated by Django 3.0.7 on 2021-05-05 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0010_collection_collectiondetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='dispatch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dispatch.Dispatch'),
        ),
    ]
