# Generated by Django 3.0.6 on 2020-10-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20201020_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='address',
            field=models.TextField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='address',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
