# Generated by Django 3.0.6 on 2020-10-20 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20201020_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Area'),
        ),
    ]
