# Generated by Django 3.0.6 on 2021-03-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20201020_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='phone',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='phone',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
