# Generated by Django 3.0.7 on 2020-10-19 18:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_date', models.DateField()),
                ('lr_no', models.IntegerField(blank=True, default=0)),
                ('truck_no', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]', 'Only alphanumeric characters are allowed.')])),
                ('weight', models.CharField(max_length=30, null=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('truck_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='purchase.Transportation')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='purchase.Warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_return_date', models.DateField()),
                ('truck_no', models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]', 'Only alphanumeric characters are allowed.')])),
                ('weight', models.CharField(max_length=30, null=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('truck_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='purchase.Transportation')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='purchase.Warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='SalesReturn_has_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='purchase.Product')),
                ('sales_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.SalesReturn')),
            ],
        ),
        migrations.CreateModel(
            name='Sales_has_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='purchase.Product')),
                ('sales', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.Sales')),
            ],
        ),
    ]
