# Generated by Django 3.0.7 on 2021-03-04 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20201110_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreturn',
            name='sales',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.Sales'),
        ),
    ]
