# Generated by Django 3.0.6 on 2021-03-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_salesreturn_has_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_has_product',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
